// <auto-generated />
using System;
using MarathonTraining.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarathonTraining.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413030618_AddActivityStravaFields_20260412")]
    partial class AddActivityStravaFields_20260412
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarathonTraining.Domain.Aggregates.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AthleteProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AverageHeartRateBpm")
                        .HasColumnType("int");

                    b.Property<int?>("AveragePowerWatts")
                        .HasColumnType("int");

                    b.Property<double?>("AverageSpeedMetresPerSecond")
                        .HasColumnType("float");

                    b.Property<double?>("DistanceMetres")
                        .HasColumnType("float");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("ExternalSource")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("HasHeartRate")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDevicePower")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxHeartRateBpm")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NormalisedPowerWatts")
                        .HasColumnType("int");

                    b.Property<int?>("RpeValue")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("StravaActivityId")
                        .HasColumnType("bigint");

                    b.Property<string>("StravaActivityType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TrainingWeekId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AthleteProfileId");

                    b.HasIndex("StravaActivityId")
                        .IsUnique()
                        .HasFilter("[StravaActivityId] IS NOT NULL");

                    b.HasIndex("TrainingWeekId");

                    b.HasIndex("AthleteProfileId", "StartedAt");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("MarathonTraining.Domain.Aggregates.AthleteProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CurrentPhase")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Base");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AthleteProfiles");
                });

            modelBuilder.Entity("MarathonTraining.Domain.Aggregates.StravaConnection", b =>
                {
                    b.Property<Guid>("AthleteProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StravaAthleteId")
                        .HasColumnType("bigint");

                    b.HasKey("AthleteProfileId");

                    b.ToTable("StravaConnections");
                });

            modelBuilder.Entity("MarathonTraining.Domain.Aggregates.TrainingWeek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId", "WeekStartDate")
                        .IsUnique();

                    b.ToTable("TrainingWeeks");
                });

            modelBuilder.Entity("MarathonTraining.Domain.Aggregates.Activity", b =>
                {
                    b.HasOne("MarathonTraining.Domain.Aggregates.TrainingWeek", null)
                        .WithMany("Activities")
                        .HasForeignKey("TrainingWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MarathonTraining.Domain.ValueObjects.TssScore", "TssScore", b1 =>
                        {
                            b1.Property<Guid>("ActivityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(8,2)")
                                .HasColumnName("TssScore");

                            b1.HasKey("ActivityId");

                            b1.ToTable("Activities");

                            b1.WithOwner()
                                .HasForeignKey("ActivityId");
                        });

                    b.Navigation("TssScore");
                });

            modelBuilder.Entity("MarathonTraining.Domain.Aggregates.AthleteProfile", b =>
                {
                    b.OwnsOne("MarathonTraining.Domain.ValueObjects.FunctionalThresholdPower", "Ftp", b1 =>
                        {
                            b1.Property<Guid>("AthleteProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Watts")
                                .HasColumnType("int")
                                .HasColumnName("FtpWatts");

                            b1.HasKey("AthleteProfileId");

                            b1.ToTable("AthleteProfiles");

                            b1.WithOwner()
                                .HasForeignKey("AthleteProfileId");
                        });

                    b.OwnsOne("MarathonTraining.Domain.ValueObjects.HeartRateZones", "HeartRateZones", b1 =>
                        {
                            b1.Property<Guid>("AthleteProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("MaxHr")
                                .HasColumnType("int")
                                .HasColumnName("MaxHr");

                            b1.Property<int>("RestingHr")
                                .HasColumnType("int")
                                .HasColumnName("RestingHr");

                            b1.Property<int>("ThresholdHr")
                                .HasColumnType("int")
                                .HasColumnName("ThresholdHr");

                            b1.HasKey("AthleteProfileId");

                            b1.ToTable("AthleteProfiles");

                            b1.WithOwner()
                                .HasForeignKey("AthleteProfileId");
                        });

                    b.Navigation("Ftp");

                    b.Navigation("HeartRateZones");
                });

            modelBuilder.Entity("MarathonTraining.Domain.Aggregates.StravaConnection", b =>
                {
                    b.HasOne("MarathonTraining.Domain.Aggregates.AthleteProfile", null)
                        .WithOne("StravaConnection")
                        .HasForeignKey("MarathonTraining.Domain.Aggregates.StravaConnection", "AthleteProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarathonTraining.Domain.Aggregates.AthleteProfile", b =>
                {
                    b.Navigation("StravaConnection");
                });

            modelBuilder.Entity("MarathonTraining.Domain.Aggregates.TrainingWeek", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
