// <auto-generated />
using System;
using MarathonTraining.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarathonTraining.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarathonTraining.Domain.Aggregates.AthleteProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CurrentPhase")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Base");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AthleteProfiles");
                });

            modelBuilder.Entity("MarathonTraining.Domain.Aggregates.StravaConnection", b =>
                {
                    b.Property<Guid>("AthleteProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StravaAthleteId")
                        .HasColumnType("bigint");

                    b.HasKey("AthleteProfileId");

                    b.ToTable("StravaConnections");
                });

            modelBuilder.Entity("MarathonTraining.Domain.Aggregates.AthleteProfile", b =>
                {
                    b.OwnsOne("MarathonTraining.Domain.ValueObjects.FunctionalThresholdPower", "Ftp", b1 =>
                        {
                            b1.Property<Guid>("AthleteProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Watts")
                                .HasColumnType("int")
                                .HasColumnName("FtpWatts");

                            b1.HasKey("AthleteProfileId");

                            b1.ToTable("AthleteProfiles");

                            b1.WithOwner()
                                .HasForeignKey("AthleteProfileId");
                        });

                    b.OwnsOne("MarathonTraining.Domain.ValueObjects.HeartRateZones", "HeartRateZones", b1 =>
                        {
                            b1.Property<Guid>("AthleteProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("MaxHr")
                                .HasColumnType("int")
                                .HasColumnName("MaxHr");

                            b1.Property<int>("RestingHr")
                                .HasColumnType("int")
                                .HasColumnName("RestingHr");

                            b1.Property<int>("ThresholdHr")
                                .HasColumnType("int")
                                .HasColumnName("ThresholdHr");

                            b1.HasKey("AthleteProfileId");

                            b1.ToTable("AthleteProfiles");

                            b1.WithOwner()
                                .HasForeignKey("AthleteProfileId");
                        });

                    b.Navigation("Ftp");

                    b.Navigation("HeartRateZones");
                });

            modelBuilder.Entity("MarathonTraining.Domain.Aggregates.StravaConnection", b =>
                {
                    b.HasOne("MarathonTraining.Domain.Aggregates.AthleteProfile", null)
                        .WithOne("StravaConnection")
                        .HasForeignKey("MarathonTraining.Domain.Aggregates.StravaConnection", "AthleteProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarathonTraining.Domain.Aggregates.AthleteProfile", b =>
                {
                    b.Navigation("StravaConnection");
                });
#pragma warning restore 612, 618
        }
    }
}
